//==============================================================================
// THIS CODE WAS AUTOGENERATED BY:
//    BedrockTools_Build.Generator.MinecraftBlocks.MinecraftBlockFactoryGenerator
// Do not modify, any changes will be lost when the generation tool is run again
// version: 0.2.0
//==============================================================================
using System.Collections.Generic;

namespace BedrockTools.Objects.Blocks {
    public static partial class VanillaBlockFactory {
        public static class Concrete {
            public static Block Black () => new Block(identifier:"minecraft:concrete", blockStates:"{color:\"black\"}");
            public static Block Blue () => new Block(identifier:"minecraft:concrete", blockStates:"{color:\"blue\"}");
            public static Block Brown () => new Block(identifier:"minecraft:concrete", blockStates:"{color:\"brown\"}");
            public static Block Cyan () => new Block(identifier:"minecraft:concrete", blockStates:"{color:\"cyan\"}");
            public static Block Gray () => new Block(identifier:"minecraft:concrete", blockStates:"{color:\"gray\"}");
            public static Block Green () => new Block(identifier:"minecraft:concrete", blockStates:"{color:\"green\"}");
            public static Block LightBlue () => new Block(identifier:"minecraft:concrete", blockStates:"{color:\"light_blue\"}");
            public static Block LightGray () => new Block(identifier:"minecraft:concrete", blockStates:"{color:\"silver\"}");
            public static Block Lime () => new Block(identifier:"minecraft:concrete", blockStates:"{color:\"lime\"}");
            public static Block Magenta () => new Block(identifier:"minecraft:concrete", blockStates:"{color:\"magenta\"}");
            public static Block Orange () => new Block(identifier:"minecraft:concrete", blockStates:"{color:\"orange\"}");
            public static Block Pink () => new Block(identifier:"minecraft:concrete", blockStates:"{color:\"pink\"}");
            public static Block Purple () => new Block(identifier:"minecraft:concrete", blockStates:"{color:\"purple\"}");
            public static Block Red () => new Block(identifier:"minecraft:concrete", blockStates:"{color:\"red\"}");
            public static Block White () => new Block(identifier:"minecraft:concrete", blockStates:"{color:\"white\"}");
            public static Block Yellow () => new Block(identifier:"minecraft:concrete", blockStates:"{color:\"yellow\"}");
        }
        public static class Dirt {
            public static Block Normal () => new Block(identifier:"minecraft:dirt", blockStates:"{dirt_type:\"normal\"}");
            public static Block Coarse () => new Block(identifier:"minecraft:dirt", blockStates:"{dirt_type:\"coarse\"}");
        }
        public static class Planks {
            public static Block Acacia () => new Block(identifier:"minecraft:planks", blockStates:"{wood_type:\"acacia\"}");
            public static Block Birch () => new Block(identifier:"minecraft:planks", blockStates:"{wood_type:\"birch\"}");
            public static Block Crimson () => new Block(identifier:"minecraft:crimson_planks");
            public static Block DarkOak () => new Block(identifier:"minecraft:planks", blockStates:"{wood_type:\"dark_oak\"}");
            public static Block Jungle () => new Block(identifier:"minecraft:planks", blockStates:"{wood_type:\"jungle\"}");
            public static Block Oak () => new Block(identifier:"minecraft:planks", blockStates:"{wood_type:\"oak\"}");
            public static Block Spruce () => new Block(identifier:"minecraft:planks", blockStates:"{wood_type:\"spruce\"}");
            public static Block Warped () => new Block(identifier:"minecraft:warped_planks");
        }
        public static class Prismarine {
            public static Block Bricks () => new Block(identifier:"minecraft:prismarine", blockStates:"{prismarine_block_type:\"bricks\"}");
            public static Block Dark () => new Block(identifier:"minecraft:prismarine", blockStates:"{prismarine_block_type:\"dark\"}");
            public static Block Default () => new Block(identifier:"minecraft:prismarine", blockStates:"{prismarine_block_type:\"default\"}");
        }
        public static class QuartzBlock {
            public static Block Chiseled () => new Block(identifier:"minecraft:quartz_bricks", blockStates:"{chisel_type:\"chiseled\"}");
            public static Block Smooth () => new Block(identifier:"minecraft:quartz_bricks", blockStates:"{chisel_type:\"smooth\"}");
            public static Block Normal () => new Block(identifier:"minecraft:quartz_bricks", blockStates:"{chisel_type:\"default\"}");
        }
        public static class StainedGlass {
            public static Block Black () => new Block(identifier:"minecraft:stained_glass", blockStates:"{color:\"black\"}");
            public static Block Blue () => new Block(identifier:"minecraft:stained_glass", blockStates:"{color:\"blue\"}");
            public static Block Brown () => new Block(identifier:"minecraft:stained_glass", blockStates:"{color:\"brown\"}");
            public static Block Cyan () => new Block(identifier:"minecraft:stained_glass", blockStates:"{color:\"cyan\"}");
            public static Block Gray () => new Block(identifier:"minecraft:stained_glass", blockStates:"{color:\"gray\"}");
            public static Block Green () => new Block(identifier:"minecraft:stained_glass", blockStates:"{color:\"green\"}");
            public static Block LightBlue () => new Block(identifier:"minecraft:stained_glass", blockStates:"{color:\"light_blue\"}");
            public static Block LightGray () => new Block(identifier:"minecraft:stained_glass", blockStates:"{color:\"silver\"}");
            public static Block Lime () => new Block(identifier:"minecraft:stained_glass", blockStates:"{color:\"lime\"}");
            public static Block Magenta () => new Block(identifier:"minecraft:stained_glass", blockStates:"{color:\"magenta\"}");
            public static Block Orange () => new Block(identifier:"minecraft:stained_glass", blockStates:"{color:\"orange\"}");
            public static Block Pink () => new Block(identifier:"minecraft:stained_glass", blockStates:"{color:\"pink\"}");
            public static Block Purple () => new Block(identifier:"minecraft:stained_glass", blockStates:"{color:\"purple\"}");
            public static Block Red () => new Block(identifier:"minecraft:stained_glass", blockStates:"{color:\"red\"}");
            public static Block White () => new Block(identifier:"minecraft:stained_glass", blockStates:"{color:\"white\"}");
            public static Block Yellow () => new Block(identifier:"minecraft:stained_glass", blockStates:"{color:\"yellow\"}");
        }
        public static class Stone {
            public static Block Andesite () => new Block(identifier:"minecraft:stone", blockStates:"{stone_type:\"andesite\"}");
            public static Block AndesiteSmooth () => new Block(identifier:"minecraft:stone", blockStates:"{stone_type:\"andesite_smooth\"}");
            public static Block Diorite () => new Block(identifier:"minecraft:stone", blockStates:"{stone_type:\"diorite\"}");
            public static Block DioriteSmooth () => new Block(identifier:"minecraft:stone", blockStates:"{stone_type:\"diorite_smooth\"}");
            public static Block Granite () => new Block(identifier:"minecraft:stone", blockStates:"{stone_type:\"granite\"}");
            public static Block GraniteSmooth () => new Block(identifier:"minecraft:stone", blockStates:"{stone_type:\"granite_smooth\"}");
            public static Block Normal () => new Block(identifier:"minecraft:stone", blockStates:"{stone_type:\"stone\"}");
        }
        public static class StoneBricks {
            public static Block Chiseled () => new Block(identifier:"minecraft:stonebrick", blockStates:"{stone_brick_type:\"chiseled\"}");
            public static Block Cracked () => new Block(identifier:"minecraft:stonebrick", blockStates:"{stone_brick_type:\"cracked\"}");
            public static Block Mossy () => new Block(identifier:"minecraft:stonebrick", blockStates:"{stone_brick_type:\"mossy\"}");
            public static Block Normal () => new Block(identifier:"minecraft:stonebrick", blockStates:"{stone_brick_type:\"default\"}");
            public static Block Smooth () => new Block(identifier:"minecraft:stonebrick", blockStates:"{stone_brick_type:\"smooth\"}");
        }
        public static class Wool {
            public static Block Black () => new Block(identifier:"minecraft:wool", blockStates:"{color:\"black\"}");
            public static Block Blue () => new Block(identifier:"minecraft:wool", blockStates:"{color:\"blue\"}");
            public static Block Brown () => new Block(identifier:"minecraft:wool", blockStates:"{color:\"brown\"}");
            public static Block Cyan () => new Block(identifier:"minecraft:wool", blockStates:"{color:\"cyan\"}");
            public static Block Gray () => new Block(identifier:"minecraft:wool", blockStates:"{color:\"gray\"}");
            public static Block Green () => new Block(identifier:"minecraft:wool", blockStates:"{color:\"green\"}");
            public static Block LightBlue () => new Block(identifier:"minecraft:wool", blockStates:"{color:\"light_blue\"}");
            public static Block LightGray () => new Block(identifier:"minecraft:wool", blockStates:"{color:\"silver\"}");
            public static Block Lime () => new Block(identifier:"minecraft:wool", blockStates:"{color:\"lime\"}");
            public static Block Magenta () => new Block(identifier:"minecraft:wool", blockStates:"{color:\"magenta\"}");
            public static Block Orange () => new Block(identifier:"minecraft:wool", blockStates:"{color:\"orange\"}");
            public static Block Pink () => new Block(identifier:"minecraft:wool", blockStates:"{color:\"pink\"}");
            public static Block Purple () => new Block(identifier:"minecraft:wool", blockStates:"{color:\"purple\"}");
            public static Block Red () => new Block(identifier:"minecraft:wool", blockStates:"{color:\"red\"}");
            public static Block White () => new Block(identifier:"minecraft:wool", blockStates:"{color:\"white\"}");
            public static Block Yellow () => new Block(identifier:"minecraft:wool", blockStates:"{color:\"yellow\"}");
        }
        public static Block Air () => new Block(identifier:"minecraft:air");
        public static Block AncientDebris () => new Block(identifier:"minecraft:ancient_debris");
        public static Block BlackStone () => new Block(identifier:"minecraft:blackstone");
        public static Block BlueIce () => new Block(identifier:"minecraft:blue_ice");
        public static Block BrickBlock () => new Block(identifier:"minecraft:brick_block");
        public static Block Clay () => new Block(identifier:"minecraft:clay");
        public static Block ChiseledNetherBricks () => new Block(identifier:"minecraft:chiseled_nether_bricks");
        public static Block ChiseledPolishedBlackstone () => new Block(identifier:"minecraft:chiseled_polished_blackstone");
        public static Block CrackedNetherBricks () => new Block(identifier:"minecraft:cracked_nether_bricks");
        public static Block CrackePolishedBlackstoneBricks () => new Block(identifier:"minecraft:cracked_polished_blackstone_bricks");
        public static Block EndBricks () => new Block(identifier:"minecraft:end_bricks");
        public static Block EndStone () => new Block(identifier:"minecraft:end_stone");
        public static Block Glass () => new Block(identifier:"minecraft:glass");
        public static Block Grass () => new Block(identifier:"minecraft:grass");
        public static Block Ice () => new Block(identifier:"minecraft:ice");
        public static Block NetherBricks () => new Block(identifier:"minecraft:nether_brick");
        public static Block PackedIce () => new Block(identifier:"minecraft:packed_ice");
        public static Block PolishedBlackstoneBricks () => new Block(identifier:"minecraft:polished_blackstone_bricks");
        public static Block QuartzBricks () => new Block(identifier:"minecraft:quartz_bricks");
    }
}
