//==============================================================================
// THIS CODE WAS AUTOGENERATED BY:
//    BedrockTools_Build.Generator.MinecraftBlocks.MinecraftBlockFactoryGenerator
// Do not modify, any changes will be lost when the generation tool is run again
// version: 1.0.1
//==============================================================================
using BedrockTools.Objects.Blocks.Minecraft;
using BedrockTools.Objects.Blocks.Util;

namespace BedrockTools.Objects.Blocks {
    public static partial class VanillaBlockFactory {
        public static UnitBlock Air () {
            return new UnitBlock ("minecraft:air");
        }
        public static PlanksBlock Planks (PlanksBlock.PlanksType variation) {
            return new PlanksBlock ("minecraft:planks", variation);
        }
        public static UnitBlock CrimsonPlanks () {
            return new UnitBlock ("minecraft:warped_planks");
        }
        public static UnitBlock WarpedPlanks () {
            return new UnitBlock ("minecraft:warped_planks");
        }
        public static UnitBlock MangrovePlanks () {
            return new UnitBlock ("minecraft:mangrove_planks");
        }
        public static StairsBlock NormalStoneStairs (BlockOrientation orientation, bool isUpsideDown = false) {
            return new StairsBlock ("minecraft:normal_stone_stairs", orientation, isUpsideDown);
        }
        public static StairsBlock StoneStairs (BlockOrientation orientation, bool isUpsideDown = false) {
            return new StairsBlock ("minecraft:stone_stairs", orientation, isUpsideDown);
        }
        public static StairsBlock MossyCobblestoneStairs (BlockOrientation orientation, bool isUpsideDown = false) {
            return new StairsBlock ("minecraft:mossy_cobblestone_stairs", orientation, isUpsideDown);
        }
        public static StairsBlock OakStairs (BlockOrientation orientation, bool isUpsideDown = false) {
            return new StairsBlock ("minecraft:oak_stairs", orientation, isUpsideDown);
        }
        public static StairsBlock SpruceStairs (BlockOrientation orientation, bool isUpsideDown = false) {
            return new StairsBlock ("minecraft:spruce_stairs", orientation, isUpsideDown);
        }
        public static StairsBlock BirchStairs (BlockOrientation orientation, bool isUpsideDown = false) {
            return new StairsBlock ("minecraft:birch_stairs", orientation, isUpsideDown);
        }
        public static StairsBlock JungleStairs (BlockOrientation orientation, bool isUpsideDown = false) {
            return new StairsBlock ("minecraft:jungle_stairs", orientation, isUpsideDown);
        }
        public static StairsBlock AcaciaStairs (BlockOrientation orientation, bool isUpsideDown = false) {
            return new StairsBlock ("minecraft:acacia_stairs", orientation, isUpsideDown);
        }
        public static StairsBlock DarkOakStairs (BlockOrientation orientation, bool isUpsideDown = false) {
            return new StairsBlock ("minecraft:dark_oak_stairs", orientation, isUpsideDown);
        }
        public static StairsBlock MangroveStairs (BlockOrientation orientation, bool isUpsideDown = false) {
            return new StairsBlock ("minecraft:mangrove_stairs", orientation, isUpsideDown);
        }
        public static StairsBlock StoneBrickStairs (BlockOrientation orientation, bool isUpsideDown = false) {
            return new StairsBlock ("minecraft:stone_brick_stairs", orientation, isUpsideDown);
        }
        public static StairsBlock MossyStoneBrickStaris (BlockOrientation orientation, bool isUpsideDown = false) {
            return new StairsBlock ("minecraft:mossy_stone_brick_stairs", orientation, isUpsideDown);
        }
        public static StairsBlock GraniteStairs (BlockOrientation orientation, bool isUpsideDown = false) {
            return new StairsBlock ("minecraft:granite_stairs", orientation, isUpsideDown);
        }
        public static StairsBlock PolishedGraniteStairs (BlockOrientation orientation, bool isUpsideDown = false) {
            return new StairsBlock ("minecraft:polished_granite_stairs", orientation, isUpsideDown);
        }
        public static StairsBlock DioriteStairs (BlockOrientation orientation, bool isUpsideDown = false) {
            return new StairsBlock ("minecraft:diorite_stairs", orientation, isUpsideDown);
        }
        public static StairsBlock PolishedDioriteStairs (BlockOrientation orientation, bool isUpsideDown = false) {
            return new StairsBlock ("minecraft:polished_diorite_stairs", orientation, isUpsideDown);
        }
        public static StairsBlock AndesitesStairs (BlockOrientation orientation, bool isUpsideDown = false) {
            return new StairsBlock ("minecraft:andesite_stairs", orientation, isUpsideDown);
        }
        public static StairsBlock PolishedAndesiteStairs (BlockOrientation orientation, bool isUpsideDown = false) {
            return new StairsBlock ("minecraft:polished_andesite_stairs", orientation, isUpsideDown);
        }
        public static StairsBlock BrickStairs (BlockOrientation orientation, bool isUpsideDown = false) {
            return new StairsBlock ("minecraft:brick_stairs", orientation, isUpsideDown);
        }
        public static StairsBlock EndBrickStairs (BlockOrientation orientation, bool isUpsideDown = false) {
            return new StairsBlock ("minecraft:end_brick_stairs", orientation, isUpsideDown);
        }
        public static StairsBlock CrimsonStairs (BlockOrientation orientation, bool isUpsideDown = false) {
            return new StairsBlock ("minecraft:crimson_stairs", orientation, isUpsideDown);
        }
        public static StairsBlock WarpedStairs (BlockOrientation orientation, bool isUpsideDown = false) {
            return new StairsBlock ("minecraft:warped_stairs", orientation, isUpsideDown);
        }
        public static UnitBlock Glass () {
            return new UnitBlock ("minecraft:glass");
        }
        public static ColorBlock StainedGlass (BlockColorValue color) {
            return new ColorBlock ("minecraft:stained_glass", color);
        }
        public static UnitBlock BrickBlock () {
            return new UnitBlock ("minecraft:brick_block");
        }
        public static UnitBlock QuartzBricks () {
            return new UnitBlock ("minecraft:quartz_bricks");
        }
        public static UnitBlock ChiseledNetherBricks () {
            return new UnitBlock ("minecraft:chiseled_nether_bricks");
        }
        public static UnitBlock CrackedNetherBricks () {
            return new UnitBlock ("minecraft:cracked_nether_bricks");
        }
        public static StoneBricksBlock StoneBricks (StoneBricksBlock.StoneBricksType variation) {
            return new StoneBricksBlock ("minecraft:stonebrick", variation);
        }
        public static UnitBlock EndBricks () {
            return new UnitBlock ("minecraft:end_bricks");
        }
        public static UnitBlock PolishedBlackstoneBricks () {
            return new UnitBlock ("minecraft:polished_blackstone_bricks");
        }
        public static UnitBlock CrackePolishedBlackstoneBricks () {
            return new UnitBlock ("minecraft:cracked_polished_blackstone_bricks");
        }
        public static UnitBlock ChiseledPolishedBlackstone () {
            return new UnitBlock ("minecraft:chiseled_polished_blackstone");
        }
        public static UnitBlock Cobblestone () {
            return new UnitBlock ("minecraft:cobblestone");
        }
        public static UnitBlock MossyCobblestone () {
            return new UnitBlock ("minecraft:mossy_cobblestone");
        }
        public static UnitBlock CobbledDeepslate () {
            return new UnitBlock ("minecraft:cobbled_deepslate");
        }
        public static UnitBlock SmoothStone () {
            return new UnitBlock ("minecraft:smooth_stone");
        }
        public static UnitBlock CoalBlock () {
            return new UnitBlock ("minecraft:coal_block");
        }
        public static UnitBlock DriedKelpBlock () {
            return new UnitBlock ("minecraft:dried_kelp_block");
        }
        public static QuartzBlock Quartz (QuartzBlock.QuartzType variation) {
            return new QuartzBlock ("minecraft:quartz_block", variation);
        }
        public static PrismarineBlock Prismarine (PrismarineBlock.PrismarineType variation) {
            return new PrismarineBlock ("minecraft:prismarine", variation);
        }
        public static UnitBlock NetherBrick () {
            return new UnitBlock ("minecraft:nether_brick");
        }
        public static UnitBlock RedNetherBrick () {
            return new UnitBlock ("minecraft:red_nether_brick");
        }
        public static ColorBlock Wool (BlockColorValue color) {
            return new ColorBlock ("minecraft:wool", color);
        }
        public static ColorBlock Carpet (BlockColorValue color) {
            return new ColorBlock ("minecraft:carpet", color);
        }
        public static ColorBlock ConcretePowder (BlockColorValue color) {
            return new ColorBlock ("minecraft:concrete_powder", color);
        }
        public static ColorBlock Concrete (BlockColorValue color) {
            return new ColorBlock ("minecraft:concrete", color);
        }
        public static UnitBlock Clay () {
            return new UnitBlock ("minecraft:clay");
        }
        public static UnitBlock HardenedClay () {
            return new UnitBlock ("minecraft:hardened_clay");
        }
        public static ColorBlock StainedHardenedClay (BlockColorValue color) {
            return new ColorBlock ("minecraft:stained_hardened_clay", color);
        }
        public static UnitBlock Purpur () {
            return new UnitBlock ("minecraft:purpur_block");
        }
        public static UnitBlock PackedMud () {
            return new UnitBlock ("minecraft:packed_mud");
        }
        public static UnitBlock MudBricks () {
            return new UnitBlock ("minecraft:mud_bricks");
        }
        public static UnitBlock AncientDebris () {
            return new UnitBlock ("minecraft:ancient_debris");
        }
        public static UnitBlock Ice () {
            return new UnitBlock ("minecraft:ice");
        }
        public static UnitBlock BlueIce () {
            return new UnitBlock ("minecraft:blue_ice");
        }
        public static UnitBlock PackedIce () {
            return new UnitBlock ("minecraft:packed_ice");
        }
        public static StoneBlock Stone (StoneBlock.StoneType variation) {
            return new StoneBlock ("minecraft:stone", variation);
        }
        public static UnitBlock EndStone () {
            return new UnitBlock ("minecraft:end_stone");
        }
        public static UnitBlock BlackStone () {
            return new UnitBlock ("minecraft:blackstone");
        }
        public static DirtBlock Dirt (DirtBlock.DirtType variation) {
            return new DirtBlock ("minecraft:dirt", variation);
        }
        public static UnitBlock Grass () {
            return new UnitBlock ("minecraft:grass");
        }
    }
}
