//==============================================================================
// THIS CODE WAS AUTOGENERATED BY @BedrockTools_Build
// Do not modify, any changes will be lost when the generation tool is run again
// Last build: 2022 - 10 - 04 16: 24:56 UTC
//==============================================================================
using System.Collections.Generic;
using BedrockTools.Objects.Blocks.Util;

namespace BedrockTools.Objects.Blocks {
    public static partial class VanillaBlockFactory {
        public static class Stairs {
            public static class Planks {
                public static StairsBlock Oak (BlockOrientation orientation, bool isUpsideDown = false)  => new StairsBlock(identifier:"minecraft:oak_stairs", orientation:orientation, isUpsideDown:isUpsideDown);
            }
        }
    }
}
