//==============================================================================
// THIS CODE WAS AUTOGENERATED BY:
//    BedrockTools_Build.Generator.MinecraftBlocks.MinecraftStairsFactoryGenerator
// Do not modify, any changes will be lost when the generation tool is run again
// version: 0.1.0
//==============================================================================
using System.Collections.Generic;
using BedrockTools.Objects.Blocks.Util;

namespace BedrockTools.Objects.Blocks {
    public static partial class VanillaBlockFactory {
        public static class Stairs {
            public static class Planks {
                public static StairsBlock Acacia (BlockOrientation orientation, bool isUpsideDown = false)  => new StairsBlock(identifier:"minecraft:acacia_stairs", orientation:orientation, isUpsideDown:isUpsideDown);
                public static StairsBlock Birch (BlockOrientation orientation, bool isUpsideDown = false)  => new StairsBlock(identifier:"minecraft:birch_stairs", orientation:orientation, isUpsideDown:isUpsideDown);
                public static StairsBlock Crimson (BlockOrientation orientation, bool isUpsideDown = false)  => new StairsBlock(identifier:"minecraft:crimson_stairs", orientation:orientation, isUpsideDown:isUpsideDown);
                public static StairsBlock DarkOak (BlockOrientation orientation, bool isUpsideDown = false)  => new StairsBlock(identifier:"minecraft:dark_oak_stairs", orientation:orientation, isUpsideDown:isUpsideDown);
                public static StairsBlock Jungle (BlockOrientation orientation, bool isUpsideDown = false)  => new StairsBlock(identifier:"minecraft:jungle_stairs", orientation:orientation, isUpsideDown:isUpsideDown);
                public static StairsBlock Oak (BlockOrientation orientation, bool isUpsideDown = false)  => new StairsBlock(identifier:"minecraft:oak_stairs", orientation:orientation, isUpsideDown:isUpsideDown);
                public static StairsBlock Spruce (BlockOrientation orientation, bool isUpsideDown = false)  => new StairsBlock(identifier:"minecraft:spruce_stairs", orientation:orientation, isUpsideDown:isUpsideDown);
                public static StairsBlock Warped (BlockOrientation orientation, bool isUpsideDown = false)  => new StairsBlock(identifier:"minecraft:warped_stairs", orientation:orientation, isUpsideDown:isUpsideDown);
            }
            public static class Stone {
                public static StairsBlock Andesite (BlockOrientation orientation, bool isUpsideDown = false)  => new StairsBlock(identifier:"minecraft:andesite_stairs", orientation:orientation, isUpsideDown:isUpsideDown);
                public static StairsBlock Diorite (BlockOrientation orientation, bool isUpsideDown = false)  => new StairsBlock(identifier:"minecraft:diorite_stairs", orientation:orientation, isUpsideDown:isUpsideDown);
                public static StairsBlock Granite (BlockOrientation orientation, bool isUpsideDown = false)  => new StairsBlock(identifier:"minecraft:granite_stairs", orientation:orientation, isUpsideDown:isUpsideDown);
                public static StairsBlock Normal (BlockOrientation orientation, bool isUpsideDown = false)  => new StairsBlock(identifier:"minecraft:normal_stone_stairs", orientation:orientation, isUpsideDown:isUpsideDown);
                public static StairsBlock PolishedAndesite (BlockOrientation orientation, bool isUpsideDown = false)  => new StairsBlock(identifier:"minecraft:polished_andesite_stairs", orientation:orientation, isUpsideDown:isUpsideDown);
                public static StairsBlock PolishedDiorite (BlockOrientation orientation, bool isUpsideDown = false)  => new StairsBlock(identifier:"minecraft:polished_diorite_stairs", orientation:orientation, isUpsideDown:isUpsideDown);
                public static StairsBlock PolishedGranite (BlockOrientation orientation, bool isUpsideDown = false)  => new StairsBlock(identifier:"minecraft:polished_granite_stairs", orientation:orientation, isUpsideDown:isUpsideDown);
            }
            public static class StoneBricks {
                public static StairsBlock Normal (BlockOrientation orientation, bool isUpsideDown = false)  => new StairsBlock(identifier:"minecraft:stone_brick_stairs", orientation:orientation, isUpsideDown:isUpsideDown);
                public static StairsBlock Mossy (BlockOrientation orientation, bool isUpsideDown = false)  => new StairsBlock(identifier:"minecraft:mossy_stone_brick_stairs", orientation:orientation, isUpsideDown:isUpsideDown);
            }
            public static StairsBlock BrickBlock (BlockOrientation orientation, bool isUpsideDown = false)  => new StairsBlock(identifier:"minecraft:brick_stairs", orientation:orientation, isUpsideDown:isUpsideDown);
            public static StairsBlock Cobblestone (BlockOrientation orientation, bool isUpsideDown = false)  => new StairsBlock(identifier:"minecraft:stone_stairs", orientation:orientation, isUpsideDown:isUpsideDown);
            public static StairsBlock EndBricks (BlockOrientation orientation, bool isUpsideDown = false)  => new StairsBlock(identifier:"minecraft:end_brick_stairs", orientation:orientation, isUpsideDown:isUpsideDown);
            public static StairsBlock MossyCoblestone (BlockOrientation orientation, bool isUpsideDown = false)  => new StairsBlock(identifier:"minecraft:mossy_cobblestone_stairs", orientation:orientation, isUpsideDown:isUpsideDown);
        }
    }
}
