// ==============================================================================
// THIS CODE WAS AUTOGENERATED BY @BedrockTools_Build
// Do not modify, any changes may be lost when the generation tool is run again
// Last build: 2022-10-01 20:46:55 UTC
// ==============================================================================


using BedrockTools.Objects.Minecraft.Blocks;

namespace BedrockTools.Objects.Minecraft.Blocks {    
    public class Air : VanillaBlock {
        public Air () : base("minecraft:air", "{}") {}
    }
}
