// ==============================================================================
// THIS CODE WAS AUTOGENERATED BY @BedrockTools_Build.Generator
// Do not modify, any changes may be lost when the generation tool is run again
// Last build: 2022-10-01 20:28:13 UTC
// ==============================================================================


namespace BlockTools.Objects.Minecraft.Blocks. {    
    public class air : VanillaBlock {
        public air () : base("Air", "{}") {}
    }
}
