// ==============================================================================
// THIS CODE WAS AUTOGENERATED BY @BedrockTools_Build.Generator
// Do not modify, any changes may be lost when the generation tool is run again
// Last build: 2022-10-01 20:41:35 UTC
// ==============================================================================


using BedrockTools.Objects.Minecraft.Blocks;

namespace BedrockTools.Objects.Minecraft.Blocks.Dirt {    
    public class Normal : VanillaBlock {
        public Normal () : base("minecraft:dirt", "{dirt_type:\"normal\"}") {}
    }
}
