// ==============================================================================
// THIS CODE WAS AUTOGENERATED BY @BedrockTools_Build
// Do not modify, any changes may be lost when the generation tool is run again
// Last build: 2022-10-02 01:25:19 UTC
// ==============================================================================


using BedrockTools.Objects.Minecraft.Blocks;

namespace BedrockTools.Objects.Minecraft.Blocks {    
    public class PlanksJungle : VanillaBlock {
        public PlanksJungle () : base("minecraft:planks", "{wood_type:\"jungle\"}") {}
    }
}
