// ==============================================================================
// THIS CODE WAS AUTOGENERATED BY @BedrockTools_Build
// Do not modify, any changes may be lost when the generation tool is run again
// Last build: 2022-10-02 05:00:22 UTC
// ==============================================================================


using BedrockTools.Objects.Minecraft.Blocks;

namespace BedrockTools.Objects.Minecraft.Blocks {    
    public class PlanksDarkOak : VanillaBlock {
        public PlanksDarkOak () : base("minecraft:planks", "{wood_type:\"dark_oak\"}") {}
    }
}
