// ==============================================================================
// THIS CODE WAS AUTOGENERATED BY @BedrockTools_Build
// Do not modify, any changes may be lost when the generation tool is run again
// Last build: 2022-10-02 05:00:22 UTC
// ==============================================================================


using BedrockTools.Objects.Minecraft.Blocks;

namespace BedrockTools.Objects.Minecraft.Blocks {    
    public class PlanksSpruce : VanillaBlock {
        public PlanksSpruce () : base("minecraft:planks", "{wood_type:\"spruce\"}") {}
    }
}
