using System;
using System.IO;

namespace BedrockTools_Build.Generator {
    abstract class Generator  {
        public string Target { get; set; }
        public ICodeGenerator CodeGenerator { get; set; }
        

        protected Generator(string target) {
            Target = target;
        }

        public virtual void WriteCode() {
            CodeBuilder builder = new CodeBuilder();
            builder
                .WriteLine("//==============================================================================")
                .WriteLine("// THIS CODE WAS AUTOGENERATED BY @BedrockTools_Build")
                .WriteLine("// Do not modify, any changes will be lost when the generation tool is run again")
                .WriteLine($"// Last build: {DateTime.UtcNow.ToString("yyyy - MM - dd HH: mm:ss")} UTC")
                .WriteLine("//==============================================================================");
            builder.Write(CodeGenerator.GetCode());
            File.WriteAllText(Path.Combine(Setting.ProjectPath, Target), builder.ToString());
        }        
    
    }
}
