using System;
using System.IO;

namespace BedrockTools_Build.Generator {
    abstract class Generator  {
        public string Target;

        protected Generator(string target) {
            Target = target;
        }

        public virtual string GetCode() {
            return
$@"// ==============================================================================
// THIS CODE WAS AUTOGENERATED BY @BedrockTools_Build.Generator
// Do not modify, any changes may be lost when the generation tool is run again
// Last build: {DateTime.UtcNow.ToString("yyyy-MM-dd HH:mm:ss")} UTC
// ==============================================================================
";
        }
        public virtual void Generate() {
            File.WriteAllText(Path.Combine(Setting.ProjectPath, Target), GetCode());
        }
    
    }
}
