//==============================================================================
// THIS CODE WAS AUTOGENERATED BY @BedrockTools_Build
// Do not modify, any changes will be lost when the generation tool is run again
// Last build: 2022 - 10 - 04 08: 38:34 UTC
//==============================================================================
using System.Collections.Generic;

namespace BedrockTools.Objects.Blocks {
    public sealed class BlocksRegistry {
        static BlocksRegistry _instance = null;
        Dictionary<string, Block> blockDictionary;

        public static BlocksRegistry Instance {
            get {
                if (_instance == null) {
                    _instance = new BlocksRegistry();
                }
                return _instance;
            }
        }

        public Block GetPrefabByName(string name) => blockDictionary[name];

        public void AddRegister(string key, Block block) {
            blockDictionary.Add(key, block);
        }

        private BlocksRegistry() {
            blockDictionary = new Dictionary<string, Block>();
            blockDictionary.Add("Air", new Block(identifier:"minecraft:air"));
            blockDictionary.Add("AncientDebris", new Block(identifier:"minecraft:ancient_debris"));
            blockDictionary.Add("BlueIce", new Block(identifier:"minecraft:blue_ice"));
            blockDictionary.Add("Clay", new Block(identifier:"minecraft:clay"));
            blockDictionary.Add("Concrete.Black", new Block(identifier:"minecraft:concrete", blockStates:"{color:\"black\"}"));
            blockDictionary.Add("Concrete.Blue", new Block(identifier:"minecraft:concrete", blockStates:"{color:\"blue\"}"));
            blockDictionary.Add("Concrete.Brown", new Block(identifier:"minecraft:concrete", blockStates:"{color:\"brown\"}"));
            blockDictionary.Add("Concrete.Cyan", new Block(identifier:"minecraft:concrete", blockStates:"{color:\"cyan\"}"));
            blockDictionary.Add("Concrete.Gray", new Block(identifier:"minecraft:concrete", blockStates:"{color:\"gray\"}"));
            blockDictionary.Add("Concrete.Green", new Block(identifier:"minecraft:concrete", blockStates:"{color:\"green\"}"));
            blockDictionary.Add("Concrete.LightBlue", new Block(identifier:"minecraft:concrete", blockStates:"{color:\"light_blue\"}"));
            blockDictionary.Add("Concrete.LightGray", new Block(identifier:"minecraft:concrete", blockStates:"{color:\"silver\"}"));
            blockDictionary.Add("Concrete.Lime", new Block(identifier:"minecraft:concrete", blockStates:"{color:\"lime\"}"));
            blockDictionary.Add("Concrete.Magenta", new Block(identifier:"minecraft:concrete", blockStates:"{color:\"magenta\"}"));
            blockDictionary.Add("Concrete.Orange", new Block(identifier:"minecraft:concrete", blockStates:"{color:\"orange\"}"));
            blockDictionary.Add("Concrete.Pink", new Block(identifier:"minecraft:concrete", blockStates:"{color:\"pink\"}"));
            blockDictionary.Add("Concrete.Purple", new Block(identifier:"minecraft:concrete", blockStates:"{color:\"purple\"}"));
            blockDictionary.Add("Concrete.Red", new Block(identifier:"minecraft:concrete", blockStates:"{color:\"red\"}"));
            blockDictionary.Add("Concrete.White", new Block(identifier:"minecraft:concrete", blockStates:"{color:\"white\"}"));
            blockDictionary.Add("Concrete.Yellow", new Block(identifier:"minecraft:concrete", blockStates:"{color:\"yellow\"}"));
            blockDictionary.Add("Dirt.Normal", new Block(identifier:"minecraft:dirt", blockStates:"{dirt_type:\"normal\"}"));
            blockDictionary.Add("Dirt.Coarse", new Block(identifier:"minecraft:dirt", blockStates:"{dirt_type:\"coarse\"}"));
            blockDictionary.Add("EndStone", new Block(identifier:"minecraft:end_stone"));
            blockDictionary.Add("Glass", new Block(identifier:"minecraft:glass"));
            blockDictionary.Add("Grass", new Block(identifier:"minecraft:grass"));
            blockDictionary.Add("Ice", new Block(identifier:"minecraft:ice"));
            blockDictionary.Add("PackedIce", new Block(identifier:"minecraft:packed_ice"));
            blockDictionary.Add("Planks.Acacia", new Block(identifier:"minecraft:planks", blockStates:"{wood_type:\"acacia\"}"));
            blockDictionary.Add("Planks.Birch", new Block(identifier:"minecraft:planks", blockStates:"{wood_type:\"birch\"}"));
            blockDictionary.Add("Planks.Crimson", new Block(identifier:"minecraft:crimson_planks"));
            blockDictionary.Add("Planks.DarkOak", new Block(identifier:"minecraft:planks", blockStates:"{wood_type:\"dark_oak\"}"));
            blockDictionary.Add("Planks.Jungle", new Block(identifier:"minecraft:planks", blockStates:"{wood_type:\"jungle\"}"));
            blockDictionary.Add("Planks.Oak", new Block(identifier:"minecraft:planks", blockStates:"{wood_type:\"oak\"}"));
            blockDictionary.Add("Planks.Spruce", new Block(identifier:"minecraft:planks", blockStates:"{wood_type:\"spruce\"}"));
            blockDictionary.Add("Planks.Warped", new Block(identifier:"minecraft:warped_planks"));
            blockDictionary.Add("Prismarine.Bricks", new Block(identifier:"minecraft:prismarine", blockStates:"{prismarine_block_type:\"bricks\"}"));
            blockDictionary.Add("Prismarine.Dark", new Block(identifier:"minecraft:prismarine", blockStates:"{prismarine_block_type:\"dark\"}"));
            blockDictionary.Add("Prismarine.Default", new Block(identifier:"minecraft:prismarine", blockStates:"{prismarine_block_type:\"default\"}"));
            blockDictionary.Add("StainedGlass.Black", new Block(identifier:"minecraft:stained_glass", blockStates:"{color:\"black\"}"));
            blockDictionary.Add("StainedGlass.Blue", new Block(identifier:"minecraft:stained_glass", blockStates:"{color:\"blue\"}"));
            blockDictionary.Add("StainedGlass.Brown", new Block(identifier:"minecraft:stained_glass", blockStates:"{color:\"brown\"}"));
            blockDictionary.Add("StainedGlass.Cyan", new Block(identifier:"minecraft:stained_glass", blockStates:"{color:\"cyan\"}"));
            blockDictionary.Add("StainedGlass.Gray", new Block(identifier:"minecraft:stained_glass", blockStates:"{color:\"gray\"}"));
            blockDictionary.Add("StainedGlass.Green", new Block(identifier:"minecraft:stained_glass", blockStates:"{color:\"green\"}"));
            blockDictionary.Add("StainedGlass.LightBlue", new Block(identifier:"minecraft:stained_glass", blockStates:"{color:\"light_blue\"}"));
            blockDictionary.Add("StainedGlass.LightGray", new Block(identifier:"minecraft:stained_glass", blockStates:"{color:\"silver\"}"));
            blockDictionary.Add("StainedGlass.Lime", new Block(identifier:"minecraft:stained_glass", blockStates:"{color:\"lime\"}"));
            blockDictionary.Add("StainedGlass.Magenta", new Block(identifier:"minecraft:stained_glass", blockStates:"{color:\"magenta\"}"));
            blockDictionary.Add("StainedGlass.Orange", new Block(identifier:"minecraft:stained_glass", blockStates:"{color:\"orange\"}"));
            blockDictionary.Add("StainedGlass.Pink", new Block(identifier:"minecraft:stained_glass", blockStates:"{color:\"pink\"}"));
            blockDictionary.Add("StainedGlass.Purple", new Block(identifier:"minecraft:stained_glass", blockStates:"{color:\"purple\"}"));
            blockDictionary.Add("StainedGlass.Red", new Block(identifier:"minecraft:stained_glass", blockStates:"{color:\"red\"}"));
            blockDictionary.Add("StainedGlass.White", new Block(identifier:"minecraft:stained_glass", blockStates:"{color:\"white\"}"));
            blockDictionary.Add("StainedGlass.Yellow", new Block(identifier:"minecraft:stained_glass", blockStates:"{color:\"yellow\"}"));
            blockDictionary.Add("Stone.Andesite", new Block(identifier:"minecraft:stone", blockStates:"{stone_type:\"andesite\"}"));
            blockDictionary.Add("Stone.AndesiteSmooth", new Block(identifier:"minecraft:stone", blockStates:"{stone_type:\"andesite_smooth\"}"));
            blockDictionary.Add("Stone.Diorite", new Block(identifier:"minecraft:stone", blockStates:"{stone_type:\"diorite\"}"));
            blockDictionary.Add("Stone.DioriteSmooth", new Block(identifier:"minecraft:stone", blockStates:"{stone_type:\"diorite_smooth\"}"));
            blockDictionary.Add("Stone.Granite", new Block(identifier:"minecraft:stone", blockStates:"{stone_type:\"granite\"}"));
            blockDictionary.Add("Stone.GraniteSmooth", new Block(identifier:"minecraft:stone", blockStates:"{stone_type:\"granite_smooth\"}"));
            blockDictionary.Add("Stone.Normal", new Block(identifier:"minecraft:stone", blockStates:"{stone_type:\"stone\"}"));
            blockDictionary.Add("Wool.Black", new Block(identifier:"minecraft:wool", blockStates:"{color:\"black\"}"));
            blockDictionary.Add("Wool.Blue", new Block(identifier:"minecraft:wool", blockStates:"{color:\"blue\"}"));
            blockDictionary.Add("Wool.Brown", new Block(identifier:"minecraft:wool", blockStates:"{color:\"brown\"}"));
            blockDictionary.Add("Wool.Cyan", new Block(identifier:"minecraft:wool", blockStates:"{color:\"cyan\"}"));
            blockDictionary.Add("Wool.Gray", new Block(identifier:"minecraft:wool", blockStates:"{color:\"gray\"}"));
            blockDictionary.Add("Wool.Green", new Block(identifier:"minecraft:wool", blockStates:"{color:\"green\"}"));
            blockDictionary.Add("Wool.LightBlue", new Block(identifier:"minecraft:wool", blockStates:"{color:\"light_blue\"}"));
            blockDictionary.Add("Wool.LightGray", new Block(identifier:"minecraft:wool", blockStates:"{color:\"silver\"}"));
            blockDictionary.Add("Wool.Lime", new Block(identifier:"minecraft:wool", blockStates:"{color:\"lime\"}"));
            blockDictionary.Add("Wool.Magenta", new Block(identifier:"minecraft:wool", blockStates:"{color:\"magenta\"}"));
            blockDictionary.Add("Wool.Orange", new Block(identifier:"minecraft:wool", blockStates:"{color:\"orange\"}"));
            blockDictionary.Add("Wool.Pink", new Block(identifier:"minecraft:wool", blockStates:"{color:\"pink\"}"));
            blockDictionary.Add("Wool.Purple", new Block(identifier:"minecraft:wool", blockStates:"{color:\"purple\"}"));
            blockDictionary.Add("Wool.Red", new Block(identifier:"minecraft:wool", blockStates:"{color:\"red\"}"));
            blockDictionary.Add("Wool.White", new Block(identifier:"minecraft:wool", blockStates:"{color:\"white\"}"));
            blockDictionary.Add("Wool.Yellow", new Block(identifier:"minecraft:wool", blockStates:"{color:\"yellow\"}"));
        }
    }
}
