
// ==============================================================================
// THIS CODE WAS AUTOGENERATED BY @BedrockTools_Build
// Do not modify, any changes may be lost when the generation tool is run again
// Last build: 2022-10-01 20:42:51 UTC
// ==============================================================================

using System;
using System.Collections.Generic;

namespace BedrockTools.Objects {

    public sealed class MinecraftBlockPrefabs {
        static MinecraftBlockPrefabs _instance = null;
        Dictionary<string, Block> blockDictionary;

        public static MinecraftBlockPrefabs Instance {
            get {
                if (_instance == null)
                    _instance = new MinecraftBlockPrefabs();
                return _instance;
            }
        }

        public Block GetPrefabByName(string name) {
            return blockDictionary[name];
        }

        private MinecraftBlockPrefabs() {
            this.blockDictionary = new Dictionary<string, Block>();
            blockDictionary.Add("Air", new BedrockTools.Objects.Minecraft.Blocks.Air());
            blockDictionary.Add("Dirt.Normal", new BedrockTools.Objects.Minecraft.Blocks.Dirt.Normal());

        }
    }
}
