
// ==============================================================================
// THIS CODE WAS AUTOGENERATED BY @BedrockTools_Build
// Do not modify, any changes may be lost when the generation tool is run again
// Last build: 2022-10-02 01:25:19 UTC
// ==============================================================================

using System;
using System.Collections.Generic;

namespace BedrockTools.Objects.Minecraft {

    public sealed class MinecraftBlockPrefabs {
        static MinecraftBlockPrefabs _instance = null;
        Dictionary<string, Block> blockDictionary;

        public static MinecraftBlockPrefabs Instance {
            get {
                if (_instance == null)
                    _instance = new MinecraftBlockPrefabs();
                return _instance;
            }
        }

        public Block GetPrefabByName(string name) {
            return blockDictionary[name];
        }

        private MinecraftBlockPrefabs() {
            this.blockDictionary = new Dictionary<string, Block>();
            blockDictionary.Add("Air", new BedrockTools.Objects.Minecraft.Blocks.Air());
            blockDictionary.Add("DirtNormal", new BedrockTools.Objects.Minecraft.Blocks.DirtNormal());
            blockDictionary.Add("DirtCoarse", new BedrockTools.Objects.Minecraft.Blocks.DirtCoarse());
            blockDictionary.Add("PlanksAcacia", new BedrockTools.Objects.Minecraft.Blocks.PlanksAcacia());
            blockDictionary.Add("PlanksBirch", new BedrockTools.Objects.Minecraft.Blocks.PlanksBirch());
            blockDictionary.Add("PlanksCrimson", new BedrockTools.Objects.Minecraft.Blocks.PlanksCrimson());
            blockDictionary.Add("PlanksDarkOak", new BedrockTools.Objects.Minecraft.Blocks.PlanksDarkOak());
            blockDictionary.Add("PlanksJungle", new BedrockTools.Objects.Minecraft.Blocks.PlanksJungle());
            blockDictionary.Add("PlanksOak", new BedrockTools.Objects.Minecraft.Blocks.PlanksOak());
            blockDictionary.Add("PlanksSpruce", new BedrockTools.Objects.Minecraft.Blocks.PlanksSpruce());
            blockDictionary.Add("PlanksWarped", new BedrockTools.Objects.Minecraft.Blocks.PlanksWarped());

        }
    }
}
