//==============================================================================
// THIS CODE WAS AUTOGENERATED BY:
//    BedrockTools_Build.Generator.MinecraftBlocks.VariationGenerator
// Do not modify, any changes will be lost when the generation tool is run again
// version: 0.1.0
//==============================================================================
using BedrockTools.Nbt.Elements;

namespace BedrockTools.Objects.Blocks.Minecraft {
    public class PlanksBlock : Block {
        public readonly PlanksType Variation;

        public PlanksBlock (string identifier, PlanksType variation) : base(identifier) {
            Variation = variation;
        }

        public override NbtCompoundSorted GetBlockState () {
            return new NbtCompoundSorted() {
                {"wood_type", (NbtString)Variation.ToString().ToLower()}
            };
        }

        public enum PlanksType {
            Oak,
            Acacia,
            Birch,
            Jungle,
            Dark_Oak,
            Spruce
        }

    }
}
