//==============================================================================
// THIS CODE WAS AUTOGENERATED BY:
//    BedrockTools_Build.Generator.MinecraftBlocks.VariationGenerator
// Do not modify, any changes will be lost when the generation tool is run again
// version: 0.1.0
//==============================================================================
using BedrockTools.Nbt.Elements;

namespace BedrockTools.Objects.Blocks.Minecraft {
    public class TallGrassBlock : Block {
        public readonly TallGrassType Variation;

        public TallGrassBlock (string identifier, TallGrassType variation) : base(identifier) {
            Variation = variation;
        }

        public override NbtCompoundSorted GetBlockState () {
            return new NbtCompoundSorted() {
                {"tall_grass_type", (NbtString)Variation.ToString().ToLower()}
            };
        }

        public enum TallGrassType {
            Default,
            Tall,
            Fern,
            Snow
        }

    }
}
